### ISSUE TITLE
CSS File not emitted on watch

### ISSUE THREAD

**Issue by dpogni** [infielddigital/aem-webpack-example#24]
See issue:
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/23#issuecomment-373939895

**Comment by kevinweber** [comment]
For now, I've disabled caching so it only runs when Webpack in production mode.
I'm hoping that @evilebottnawi or someone else from the `mini-css-extract-plugin` team is working on a fix for their plugin.

**Comment by evilebottnawi** [comment]
@kevinweber in this week i take care about this :+1:

**Comment by kevinweber** [comment]
Fixed with #28.
