### ISSUE TITLE
File to import not found or unreadable: scss/variables

### ISSUE THREAD

**Issue by lunanigra** [infielddigital/aem-webpack-example#35]
Hello and thanks for your great module!

I have some trouble getting your sample config running. Our project was originally set up via Maven...
https://helpx.adobe.com/experience-manager/using/maven_arch13.html#CreateanAEMMaven13archetypeproject

Then I copied your sample folders/files into our project.

Can you please check if I missed some point or if your documentation needs an update (or a hint)?

```
ERROR in ../content/jcr_root/apps/AEMMaven13/components/example-component/webpack.module/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'scss/variables';
^
      File to import not found or unreadable: scss/variables.
      in /Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/content/jcr_root/apps/AEMMaven13/components/example-component/webpack.module/index.scss (line 1, column 1)
    at runLoaders (/Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/webpack/lib/NormalModule.js:303:20)
    at /Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/webpack.core/node_modules/node-sass/lib/index.js:294:32)
 @ ../content/jcr_root/apps/AEMMaven13/components/example-component/webpack.module/index.js 5:0-23
 @ ../content/jcr_root sync \/webpack\.module\/index\.js$
 @ ../webpack.project/entries/components.js

ERROR in ../content/jcr_root/apps/AEMMaven13/components/example-component/webpack.module/index.js
Module not found: Error: Can't resolve 'js/utils' in '/Users/[user]/IdeaProjects/AEMMaven13/ui.apps/src/main/content/jcr_root/apps/AEMMaven13/components/example-component/webpack.module'
 @ ../content/jcr_root/apps/AEMMaven13/components/example-component/webpack.module/index.js 3:13-32
 @ ../content/jcr_root sync \/webpack\.module\/index\.js$
 @ ../webpack.project/entries/components.js
```

**Comment by kevinweber** [comment]
Hi @lunanigra,
have you also copied the `webpack.resolve` folder from [here](https://github.com/infielddigital/aem-webpack-example/tree/master/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components), or just the example component?

**Comment by lunanigra** [comment]
Yes, the folder webpack.resolve got copied on the same level as the sample component.

So, all files should be available; but probably something wrong with the folder structure?

![image](https://user-images.githubusercontent.com/2649466/42349090-d39dcf9e-80ab-11e8-9766-48e1067d37f9.png)

**Comment by kevinweber** [comment]
Good.
Based on your screenshot: Do you have a folder `example-component` which contains another folder `webpack.module`, or is the folder name `example-component.webpack.module`? The latter would be incorrect but I suppose I'm just confused by the way your editor displays folders.

So... can you play around with the resolve path defined in webpack.config.js?
=> https://github.com/infielddigital/aem-webpack-example/blob/master/ui.apps/src/main/webpack.core/internals/webpack.config.js#L102
If you replace `CONFIG.aem.jcrRoot + '/apps/' + CONFIG.aem.projectFolderName + '/components/webpack.resolve/',` with your own and absolute path to the `webpack.resolve` folder, the issue should be solved. Then you can compare how your absolute path is different from the default path in webpack.config.js.

**Comment by lunanigra** [comment]
Thanks! I got it ;-)

The project name was not set correctly...
```
const AEM = {
  projectFolderName: 'AEMMaven13',
  ...
}
```

Cheers, JC
