### ISSUE TITLE
Is this supossed to work on Windows (cygwin or git bash)? 

### ISSUE THREAD

**Issue by jimfrenette** [infielddigital/aem-webpack-example#38]
my project is named barebones as you can see. here is were the problem starts - I could try hacking the npm scripts calls in package.json and hardcode the exec path, but wanted to send this along anyway

for mvn install ... looks like it runs okay until it hits the postinstall npm script 

[INFO] > cross-env "${npm_node_execpath}" "${npm_execpath}" rebuild node-sass
[INFO]
[ERROR] '%npm_node_execpath%' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
[ERROR] events.js:160
[ERROR]       throw er; // Unhandled 'error' event
... <snip>
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules\sane\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[ERROR] npm ERR! Windows_NT 10.0.17134
<snip>
[ERROR] npm ERR! node v7.2.1
[ERROR] npm ERR! npm  v3.10.10
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! aem-webpack-example@2.5.0 postinstall: `cross-env "${npm_node_execpath}" "${npm_execpath}" rebuild node-sass`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the aem-webpack-example@2.5.0 postinstall script 'cross-env "${npm_node_execpath}" "${npm_execpath}" rebuild node-sass'.

<snip>

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] barebones 1.0-SNAPSHOT ............................. SUCCESS [  0.474 s]
[INFO] barebones - Core ................................... SUCCESS [  4.910 s]
[INFO] barebones - UI apps ................................ FAILURE [04:51 min]
[INFO] barebones - UI content ............................. SKIPPED
[INFO] barebones - Integration Tests Bundles .............. SKIPPED
[INFO] barebones - Integration Tests Launcher 1.0-SNAPSHOT  SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by jmagner** [comment]
+1

**Comment by kevinweber** [comment]
I remember that @rkeenan tested the setup on Windows and it worked for him. Maybe some dependency got updated or incompatible with Windows?

Have either of you, @jimfrenette or @jmagner, used this setup before and had it working?

The current setup has an outdated version of the `cross-env` package. Can you try updating it to the latest version and check if that changes anything? (`npm install -D cross-env@^5.2.0`)

Since I can't reproduce your issue, it would be helpful if one of you can investigate and share your solution :-)

**Comment by kevinweber** [comment]
@id-pogni The reason why we added "npm_node_execpath" was because some continuous deployment tools didn't work with just "npm".

@jimfrenette, please let us know if @id-pogni's suggestion fixes your issue.

**Comment by jmagner** [comment]
@kevinweber I am implementing this project for the first time, so I can't say if it is a new issue or not. In the mean time, I was able to get it to work by using cross-env on the npm scripts that weren't using it (start, build, etc), and replacing exec path with npm. Is there a reason cross-env isn't included in the npm start task?

**Comment by jimfrenette** [comment]
@kevinweber, @id-pogni, using npm command instead of those nodexec path vars worked, thanks.

**Comment by kevinweber** [comment]
Thanks @jimfrenette @jmagner @dpogni. I've updated the code accordingly:
https://github.com/infielddigital/aem-webpack-example/pull/40
