### ISSUE TITLE
Easier frontend integration with AEM

### ISSUE THREAD

**Issue by kulek1** [infielddigital/aem-webpack-example#42]
Hi, 
I've found your configuration in Google and I thought that maybe you will get acquainted with my plugin. It makes the whole process much easier because you might have only one webpack config with all configuration as you wish.

The basic idea is to have separate and independent modules (Clientlibs) with frontend workflow as we know. You can add `AemSyncPlugin` and `LiveReloadPlugin` easily as well. 

[Multiple Bundles Webpack Plugin](https://github.com/kulek1/multiple-bundles-webpack-plugin)

Let me know what you think.
Cheers

**Comment by kevinweber** [comment]
Thanks for your suggestion. We've figured out a similar solution where one output/clientlib gets generated per component (instead of one output/clientlib for all components). However, I don't plan on adding this functionality to this project yet.
