### ISSUE TITLE
npmVersion should be specified

### ISSUE THREAD

**Issue by justinedelson** [infielddigital/aem-webpack-example#53]
Due to https://github.com/eirslett/frontend-maven-plugin/issues/560, the frontend-maven-plugin doesn't operate well in cases where node/npm is *not* installed on the system (and, in fact, you could argue that it doesn't operate well even when those are installed on the system since running npm from npm would result in the system npm being called, not the plugin-managed one).

As such, it would be best if this project (which is great BTW) would specify npmVersion in the ui.apps/pom.xml file.

Of course, it would be better if that bug was fixed, but it has been open for 2 years.

**Comment by gaetanmarmasse** [comment]
Hi Justin, 
Good point! We'll start looking into adding this. 
Thanks for the feedback.

**Comment by gaetanmarmasse** [comment]
Fix added by https://github.com/infielddigital/aem-webpack-example/pull/54.
