### ISSUE TITLE
ttab module not compatible with Linux

### ISSUE THREAD

**Issue by rkeenan** [infielddigital/aem-webpack-example#6]
When trying to run webpack in a Linux environment, it does not actually work because the [ttab npm module](https://www.npmjs.com/package/ttab) does not support Linux. I think an alternative should be found!
Error below:
```[INFO] Running 'yarn install' in /usr/src/mymaven/ui.apps/src/main/webpack
[INFO] yarn install v0.20.3
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[ERROR] error ttab@0.6.0: The platform "linux" is incompatible with this module.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ERROR] error Found incompatible module

**Comment by sljones1** [comment]
@kevinweber could you rewrite the commands to use `screen`? That is a command that is OS agnostic (it ships with GNU)

**Comment by kevinweber** [comment]
@sljones1 Can you give an example? This is what I want to achieve in one command:

1. Open new tab/window & run a command
2. Open another window (or stay in original window) & run a different command.

Both commands should run in parallel in different windows and not affect each other.

**Comment by sljones1** [comment]
https://unix.stackexchange.com/questions/108222/linux-sending-a-command-to-a-screen-through-a-shell-script

So "window" will be very hard because flavors of linux each have different terminal commands. What screen does is simulate a new window and runs in the background. It terminates once done.
