### ISSUE TITLE
NPM not found issue

### ISSUE THREAD

**Issue by rkeenan** [infielddigital/aem-webpack-example#7]
When building (again on a remote CI server), I ran into an issue where NPM is not installed. Locally it works fine because I have NPM installed on my machine, but it's not set up on the remote server. I think switching over to NPM instead of yarn may resolve the issue.

**Comment by kevinweber** [comment]
The best solution might be to pick either npm or Yarn. Right now, we use Yarn as part of Maven and NPM in package.json. That works well on a local machine that has Yarn and NPM installed but – as @rkeenan discovered – might not work on a remote server. We'll think about it. Any suggestions/recommendations are welcome. (Yarn or NPM?)

**Comment by kevinweber** [comment]
After collecting feedback from several developers, it's likely we'll get rid of Yarn and only use NPM.

**Comment by shoelessone** [comment]
:thumbsup:
